const { PDFDocument, StandardFonts, rgb } = require("pdf-lib");

const SchoolTuitionPayment = require("../models/SchoolTuitionPayment");

const createServiceError = (message, status = 400) => {
  const error = new Error(message);
  error.status = status;
  error.statusCode = status;
  error.isOperational = true;
  return error;
};

const toText = (value = "", maxLength = 240) =>
  String(value || "").trim().replace(/\s+/g, " ").slice(0, maxLength);

const toPdfText = (value = "") =>
  toText(value, 500)
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^\x20-\x7E]/g, "?");

const formatMoney = (amount = 0, currency = "NGN") =>
  `${toPdfText(currency || "NGN")} ${Number(amount || 0).toLocaleString("en-NG", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;

const formatDate = (value) => {
  const date = value ? new Date(value) : null;
  if (!date || Number.isNaN(date.getTime())) return "-";
  return new Intl.DateTimeFormat("en-NG", {
    dateStyle: "medium",
    timeStyle: "short",
    timeZone: "Africa/Lagos",
  }).format(date);
};

const wrapText = ({ text = "", font, size = 11, maxWidth = 430 }) => {
  const words = toPdfText(text).split(/\s+/).filter(Boolean);
  const lines = [];
  let line = "";
  words.forEach((word) => {
    const next = line ? `${line} ${word}` : word;
    if (line && font.widthOfTextAtSize(next, size) > maxWidth) {
      lines.push(line);
      line = word;
    } else {
      line = next;
    }
  });
  if (line) lines.push(line);
  return lines.length ? lines : [""];
};

const buildSchoolTuitionReceiptPdf = async (payment = {}) => {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595.28, 841.89]);
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const dark = rgb(0.04, 0.11, 0.08);
  const green = rgb(0.08, 0.42, 0.23);
  const gold = rgb(0.91, 0.69, 0.13);
  const muted = rgb(0.35, 0.39, 0.37);
  const pale = rgb(0.96, 0.98, 0.96);
  const margin = 48;
  const width = page.getWidth() - (margin * 2);

  page.drawRectangle({ x: 0, y: 720, width: page.getWidth(), height: 122, color: dark });
  page.drawRectangle({ x: 0, y: 714, width: page.getWidth(), height: 6, color: gold });
  page.drawText("TENGACION", { x: margin, y: 798, size: 11, font: bold, color: gold });
  page.drawText("ONLINE TUITION PAYMENT RECEIPT", { x: margin, y: 762, size: 20, font: bold, color: rgb(1, 1, 1) });
  page.drawText("Verified payment record", { x: margin, y: 739, size: 11, font: regular, color: rgb(0.82, 0.87, 0.84) });

  page.drawRectangle({ x: margin, y: 642, width, height: 48, color: pale, borderColor: rgb(0.82, 0.88, 0.84), borderWidth: 1 });
  page.drawText("PAYMENT CONFIRMED", { x: margin + 16, y: 660, size: 13, font: bold, color: green });
  page.drawText(formatMoney(payment.amount, payment.currency), {
    x: margin + width - 190,
    y: 658,
    size: 16,
    font: bold,
    color: dark,
  });

  let y = 602;
  const drawField = (label, value) => {
    page.drawText(toPdfText(label).toUpperCase(), { x: margin, y, size: 8.5, font: bold, color: muted });
    const lines = wrapText({ text: value || "-", font: regular, size: 11.5, maxWidth: width - 170 });
    lines.forEach((line, index) => {
      page.drawText(line, { x: margin + 170, y: y - (index * 15), size: 11.5, font: regular, color: dark });
    });
    const rowHeight = Math.max(34, 18 + ((lines.length - 1) * 15));
    page.drawLine({
      start: { x: margin, y: y - rowHeight + 10 },
      end: { x: margin + width, y: y - rowHeight + 10 },
      thickness: 0.6,
      color: rgb(0.86, 0.88, 0.87),
    });
    y -= rowHeight;
  };

  drawField("School", payment.schoolName);
  drawField("Parent / guardian", payment.parentName);
  drawField("Learner", payment.childName);
  drawField("Class", payment.childClass);
  drawField("Amount", formatMoney(payment.amount, payment.currency));
  drawField("Payment date", formatDate(payment.paidAt));
  drawField("Payment channel", payment.paymentChannel || "Paystack");
  drawField("Bank", payment.verifiedBankName || payment.bankName || "Not reported");
  drawField("Paystack reference", payment.reference);

  const footerY = 94;
  page.drawLine({
    start: { x: margin, y: footerY + 42 },
    end: { x: margin + width, y: footerY + 42 },
    thickness: 1,
    color: gold,
  });
  page.drawText("Generated by Tengacion after server-side Paystack verification.", {
    x: margin,
    y: footerY + 20,
    size: 9.5,
    font: regular,
    color: muted,
  });
  page.drawText("Keep this receipt and reference for school payment enquiries. No card, PIN, or OTP data is stored.", {
    x: margin,
    y: footerY,
    size: 8.5,
    font: regular,
    color: muted,
  });

  pdf.setTitle(`${toPdfText(payment.schoolName)} Tuition Receipt`);
  pdf.setSubject("Verified online tuition payment receipt");
  pdf.setCreator("Tengacion");
  pdf.setProducer("Tengacion");

  return Buffer.from(await pdf.save());
};

const getSchoolTuitionReceipt = async ({ slug = "", reference = "" } = {}) => {
  const payment = await SchoolTuitionPayment.findOne({
    schoolSlug: toText(slug, 120).toLowerCase(),
    reference: toText(reference, 180),
  }).lean();
  if (!payment) {
    throw createServiceError("Tuition payment not found", 404);
  }
  if (payment.status !== "paid") {
    throw createServiceError("A receipt is available only after Paystack confirms the payment", 409);
  }

  const safeReference = String(payment.reference || "receipt").replace(/[^a-z0-9_-]+/gi, "-");
  return {
    buffer: await buildSchoolTuitionReceiptPdf(payment),
    fileName: `tuition-receipt-${safeReference}.pdf`,
  };
};

module.exports = {
  buildSchoolTuitionReceiptPdf,
  getSchoolTuitionReceipt,
};
