const NEWS_TOPIC_CATALOG = [
  {
    slug: "transport",
    displayName: "Transport",
    category: "local",
    summary: "Roads, transit changes, commuting updates, and mobility alerts.",
    regionScopes: ["local", "nigeria"],
    icon: "route",
    isFeatured: true,
    trustPriority: 0.78,
  },
  {
    slug: "safety",
    displayName: "Safety",
    category: "public-interest",
    summary: "Public safety, emergency notices, and verified incident updates.",
    regionScopes: ["local", "nigeria"],
    icon: "shield",
    isFeatured: true,
    trustPriority: 0.92,
  },
  {
    slug: "education",
    displayName: "Education",
    category: "nigeria",
    summary: "Schools, exams, policy changes, and student-focused coverage.",
    regionScopes: ["local", "nigeria"],
    icon: "book",
    isFeatured: true,
    trustPriority: 0.76,
  },
  {
    slug: "weather",
    displayName: "Weather",
    category: "local",
    summary: "Forecasts, climate alerts, rainfall warnings, and seasonal shifts.",
    regionScopes: ["local", "nigeria"],
    icon: "cloud",
    isFeatured: true,
    trustPriority: 0.9,
  },
  {
    slug: "community",
    displayName: "Community",
    category: "local",
    summary: "Neighborhood updates, services, openings, and civic life.",
    regionScopes: ["local"],
    icon: "home",
    isFeatured: true,
    trustPriority: 0.7,
  },
  {
    slug: "politics",
    displayName: "Politics",
    category: "nigeria",
    summary: "Government, elections, policy, and public accountability reporting.",
    regionScopes: ["nigeria", "world"],
    icon: "columns",
    isFeatured: true,
    trustPriority: 0.84,
  },
  {
    slug: "economy",
    displayName: "Economy",
    category: "nigeria",
    summary: "Inflation, jobs, markets, budgets, and everyday economic impact.",
    regionScopes: ["nigeria", "world"],
    icon: "chart",
    isFeatured: true,
    trustPriority: 0.82,
  },
  {
    slug: "business",
    displayName: "Business",
    category: "nigeria",
    summary: "Companies, startups, trade, entrepreneurship, and market moves.",
    regionScopes: ["nigeria", "world"],
    icon: "briefcase",
    isFeatured: true,
    trustPriority: 0.77,
  },
  {
    slug: "technology",
    displayName: "Technology",
    category: "world",
    summary: "AI, startups, product launches, policy, and internet culture.",
    regionScopes: ["nigeria", "world"],
    icon: "spark",
    isFeatured: true,
    trustPriority: 0.75,
  },
  {
    slug: "culture",
    displayName: "Culture",
    category: "nigeria",
    summary: "Arts, identity, festivals, heritage, and cultural commentary.",
    regionScopes: ["nigeria", "world"],
    icon: "palette",
    isFeatured: false,
    trustPriority: 0.68,
  },
  {
    slug: "sports",
    displayName: "Sports",
    category: "nigeria",
    summary: "Teams, leagues, tournaments, and performance stories.",
    regionScopes: ["nigeria", "world"],
    icon: "trophy",
    isFeatured: false,
    trustPriority: 0.66,
  },
  {
    slug: "entertainment",
    displayName: "Entertainment",
    category: "nigeria",
    summary: "Music, film, creators, and the stories shaping pop culture.",
    regionScopes: ["nigeria", "world"],
    icon: "mic",
    isFeatured: false,
    trustPriority: 0.64,
  },
  {
    slug: "health",
    displayName: "Health",
    category: "public-interest",
    summary: "Public health notices, disease surveillance, and verified guidance.",
    regionScopes: ["nigeria", "world"],
    icon: "heart",
    isFeatured: true,
    trustPriority: 0.9,
  },
  {
    slug: "world",
    displayName: "World",
    category: "world",
    summary: "International events with balanced source diversity.",
    regionScopes: ["world"],
    icon: "globe",
    isFeatured: true,
    trustPriority: 0.73,
  },
];

module.exports = {
  NEWS_TOPIC_CATALOG,
};
