const env = (key) => String(process.env[key] || "").trim();

const NEWS_SOURCE_CATALOG = [
  {
    slug: "reuters",
    displayName: "Reuters",
    publisherName: "Reuters",
    providerType: "reuters",
    publisherTier: "licensed",
    sourceType: "wire",
    verificationStatus: "verified",
    licenseType: "licensed_api",
    homepageUrl: "https://www.reuters.com",
    canonicalDomain: "reuters.com",
    trustScore: 0.94,
    defaultLanguage: "en",
    supportedRegions: ["world", "nigeria"],
    preferredTabs: ["for-you", "nigeria", "world"],
    categoryCoverage: ["politics", "economy", "business", "technology", "world"],
    topicTags: ["trusted", "wire", "world", "nigeria"],
    licenseNotes:
      "Requires an active Reuters license. Tengacion stores and displays only permitted summary metadata, attribution, canonical URL, and allowed thumbnails.",
    useNotes:
      "Do not ingest or render full article body unless the contract explicitly upgrades the rights mode.",
    ingest: {
      apiBaseUrl: env("NEWS_REUTERS_BASE_URL"),
      envKey: "NEWS_REUTERS_API_KEY",
      envSecret: "NEWS_REUTERS_API_SECRET",
      enabled: true,
    },
  },
  {
    slug: "ap",
    displayName: "Associated Press",
    publisherName: "Associated Press",
    providerType: "ap",
    publisherTier: "licensed",
    sourceType: "wire",
    verificationStatus: "verified",
    licenseType: "licensed_api",
    homepageUrl: "https://apnews.com",
    canonicalDomain: "apnews.com",
    trustScore: 0.92,
    defaultLanguage: "en",
    supportedRegions: ["world"],
    preferredTabs: ["for-you", "world"],
    categoryCoverage: ["world", "politics", "business", "sports"],
    topicTags: ["trusted", "wire", "world"],
    licenseNotes:
      "Use only through Tengacion's approved AP agreement. Summary-plus-link-out handling is the default mode.",
    useNotes:
      "Respect AP attribution and canonical linking on every card and detail surface.",
    ingest: {
      apiBaseUrl: env("NEWS_AP_BASE_URL"),
      envKey: "NEWS_AP_API_KEY",
      envSecret: "NEWS_AP_API_SECRET",
      enabled: true,
    },
  },
  {
    slug: "guardian",
    displayName: "The Guardian",
    publisherName: "The Guardian",
    providerType: "guardian",
    publisherTier: "partner",
    sourceType: "publisher",
    verificationStatus: "verified",
    licenseType: "licensed_api",
    homepageUrl: "https://www.theguardian.com",
    canonicalDomain: "theguardian.com",
    trustScore: 0.88,
    defaultLanguage: "en",
    supportedRegions: ["world", "nigeria"],
    preferredTabs: ["for-you", "nigeria", "world"],
    categoryCoverage: ["world", "politics", "culture", "business", "technology"],
    topicTags: ["trusted", "analysis", "world"],
    licenseNotes:
      "Use only via the official Guardian API or an approved partner distribution agreement.",
    useNotes:
      "Store headline, standfirst, byline, canonical URL, thumbnail when available, and license-safe summary only.",
    ingest: {
      apiBaseUrl: env("NEWS_GUARDIAN_BASE_URL"),
      envKey: "NEWS_GUARDIAN_API_KEY",
      envSecret: "NEWS_GUARDIAN_API_SECRET",
      enabled: true,
    },
  },
  {
    slug: "channels-tv",
    displayName: "Channels TV",
    publisherName: "Channels Television",
    providerType: "partner_rss",
    publisherTier: "partner",
    sourceType: "publisher",
    verificationStatus: "reviewed",
    licenseType: "official_rss",
    homepageUrl: "https://www.channelstv.com",
    canonicalDomain: "channelstv.com",
    trustScore: 0.84,
    countries: ["Nigeria"],
    defaultLanguage: "en",
    supportedRegions: ["nigeria"],
    preferredTabs: ["for-you", "local", "nigeria"],
    categoryCoverage: ["politics", "business", "security", "education"],
    topicTags: ["nigeria", "tv", "breaking"],
    licenseNotes:
      "Ingest only from the publisher's official RSS/feed terms or a separate Tengacion agreement.",
    useNotes:
      "Cards must link out to the canonical story page and clearly show publisher attribution.",
    ingest: {
      rssUrl: env("NEWS_CHANNELS_TV_RSS_URL"),
      envKey: "NEWS_CHANNELS_TV_RSS_URL",
      enabled: true,
    },
  },
  {
    slug: "premium-times",
    displayName: "Premium Times",
    publisherName: "Premium Times",
    providerType: "partner_rss",
    publisherTier: "partner",
    sourceType: "publisher",
    verificationStatus: "reviewed",
    licenseType: "official_rss",
    homepageUrl: "https://www.premiumtimesng.com",
    canonicalDomain: "premiumtimesng.com",
    trustScore: 0.83,
    countries: ["Nigeria"],
    defaultLanguage: "en",
    supportedRegions: ["nigeria"],
    preferredTabs: ["for-you", "nigeria"],
    categoryCoverage: ["politics", "economy", "education", "technology"],
    topicTags: ["nigeria", "business", "technology"],
    licenseNotes:
      "Use only the publisher's approved RSS or a contracted feed. Do not scrape article pages.",
    useNotes:
      "Only metadata and summary-safe snippets should be stored in Tengacion.",
    ingest: {
      rssUrl: env("NEWS_PREMIUM_TIMES_RSS_URL"),
      envKey: "NEWS_PREMIUM_TIMES_RSS_URL",
      enabled: true,
    },
  },
  {
    slug: "lagos-traffic-radio",
    displayName: "Lagos Traffic Radio",
    publisherName: "Lagos Traffic Radio",
    providerType: "partner_rss",
    publisherTier: "partner",
    sourceType: "local",
    verificationStatus: "reviewed",
    licenseType: "official_rss",
    homepageUrl: "https://lagostrafficradio.com",
    canonicalDomain: "lagostrafficradio.com",
    trustScore: 0.81,
    countries: ["Nigeria"],
    states: ["Lagos"],
    defaultLanguage: "en",
    supportedRegions: ["local", "nigeria"],
    preferredTabs: ["local", "for-you"],
    categoryCoverage: ["transport", "safety", "community"],
    topicTags: ["local", "lagos", "transport"],
    licenseNotes:
      "Use only official feed entries, summaries, and canonical links allowed by the publisher or operating authority.",
    useNotes:
      "Best suited for local routing, commuting, and community updates.",
    ingest: {
      rssUrl: env("NEWS_LAGOS_TRAFFIC_RSS_URL"),
      envKey: "NEWS_LAGOS_TRAFFIC_RSS_URL",
      enabled: true,
    },
  },
  {
    slug: "nema-alerts",
    displayName: "NEMA Alerts",
    publisherName: "National Emergency Management Agency",
    providerType: "partner_rss",
    publisherTier: "partner",
    sourceType: "government",
    verificationStatus: "verified",
    licenseType: "public_domain",
    homepageUrl: "https://nema.gov.ng",
    canonicalDomain: "nema.gov.ng",
    trustScore: 0.89,
    countries: ["Nigeria"],
    defaultLanguage: "en",
    supportedRegions: ["local", "nigeria"],
    preferredTabs: ["local", "nigeria", "for-you"],
    categoryCoverage: ["safety", "weather", "emergency", "community"],
    topicTags: ["safety", "public-interest", "alerts"],
    licenseNotes:
      "Government/public-interest notices may be used with attribution, canonical links, and careful source preservation.",
    useNotes:
      "Prioritize for critical service and safety updates when available.",
    ingest: {
      rssUrl: env("NEWS_NEMA_RSS_URL"),
      envKey: "NEWS_NEMA_RSS_URL",
      enabled: true,
    },
  },
  {
    slug: "nimet",
    displayName: "NiMet",
    publisherName: "Nigerian Meteorological Agency",
    providerType: "partner_rss",
    publisherTier: "partner",
    sourceType: "government",
    verificationStatus: "verified",
    licenseType: "public_domain",
    homepageUrl: "https://nimet.gov.ng",
    canonicalDomain: "nimet.gov.ng",
    trustScore: 0.87,
    countries: ["Nigeria"],
    defaultLanguage: "en",
    supportedRegions: ["local", "nigeria"],
    preferredTabs: ["local", "nigeria"],
    categoryCoverage: ["weather", "climate", "safety"],
    topicTags: ["weather", "climate", "alerts"],
    licenseNotes:
      "Use weather and climate bulletin metadata from official public feeds or licensed distribution only.",
    useNotes:
      "Useful for local forecasts, flood alerts, and transport disruption context.",
    ingest: {
      rssUrl: env("NEWS_NIMET_RSS_URL"),
      envKey: "NEWS_NIMET_RSS_URL",
      enabled: true,
    },
  },
  {
    slug: "who-africa",
    displayName: "WHO Africa",
    publisherName: "World Health Organization Africa",
    providerType: "partner_rss",
    publisherTier: "partner",
    sourceType: "ngo",
    verificationStatus: "verified",
    licenseType: "public_domain",
    homepageUrl: "https://www.afro.who.int",
    canonicalDomain: "afro.who.int",
    trustScore: 0.9,
    defaultLanguage: "en",
    supportedRegions: ["world", "nigeria"],
    preferredTabs: ["for-you", "nigeria", "world"],
    categoryCoverage: ["health", "public-interest", "world"],
    topicTags: ["health", "public-interest", "africa"],
    licenseNotes:
      "Use official public updates with attribution and canonical links. Do not treat third-party coverage as WHO-originated.",
    useNotes:
      "Good for health advisories, vaccination campaigns, and cross-border health alerts.",
    ingest: {
      rssUrl: env("NEWS_WHO_AFRICA_RSS_URL"),
      envKey: "NEWS_WHO_AFRICA_RSS_URL",
      enabled: true,
    },
  },
  {
    slug: "gdelt",
    displayName: "GDELT Discovery",
    publisherName: "GDELT",
    providerType: "gdelt",
    publisherTier: "discovery",
    sourceType: "aggregator",
    verificationStatus: "discovery",
    licenseType: "discovery",
    homepageUrl: "https://www.gdeltproject.org",
    canonicalDomain: "gdeltproject.org",
    trustScore: 0.62,
    discoveryOnly: true,
    defaultLanguage: "en",
    supportedRegions: ["world"],
    preferredTabs: ["world"],
    categoryCoverage: ["world", "monitoring"],
    topicTags: ["discovery", "world"],
    licenseNotes:
      "Discovery-only signal source. Do not treat GDELT summaries as publisher rights for article-body storage.",
    useNotes:
      "Use for source discovery and clustering support, not for dominant feed placement.",
    ingest: {
      apiBaseUrl: env("NEWS_GDELT_BASE_URL"),
      envKey: "NEWS_GDELT_API_KEY",
      envSecret: "NEWS_GDELT_API_SECRET",
      enabled: true,
    },
  },
];

module.exports = {
  NEWS_SOURCE_CATALOG,
};
