export const EMAIL = 'billylorietta@gmail.com';
export const services = [
  { title: 'Administrative support', icon: 'folder', text: 'A more organized day, with the details taken care of.', items: ['Email, calendar & scheduling', 'Data entry & database management', 'Document, file & folder organization', 'Follow-ups & everyday administration'] },
  { title: 'Operations support', icon: 'grid', text: 'Keep work moving from the first request to the final update.', items: ['Work order & purchase order tracking', 'Maintenance scheduling & equipment records', 'Operational coordination', 'Process & task tracking'] },
  { title: 'Payroll review & support', icon: 'check', text: 'Careful checks that give your payroll team clearer information.', items: ['Technician time-entry review', 'GPS & claimed-hours reconciliation', 'Exception investigation & variance notes', 'Findings prepared for management review'] },
  { title: 'Reporting & data management', icon: 'chart', text: 'Turn scattered information into reports you can act on.', items: ['Daily operations & dispatch reports', 'Excel & Google Sheets reporting', 'Data checking & reconciliation', 'Research & information gathering'] },
  { title: 'Contracts & billing admin', icon: 'file', text: 'Stay on top of the paperwork behind your client relationships.', items: ['Contract setup, updates & renewals', 'Billing information & PM billing lines', 'Cost-sheet updates', 'Proposal & document tracking'] },
  { title: 'Communication & team support', icon: 'chat', text: 'Clear communication that keeps everyone on the same page.', items: ['Client & vendor correspondence', 'Teams & Slack coordination', 'Internal follow-ups', 'Customer service & training support'] },
  { title: 'Research & hiring support', icon: 'search', text: 'Thoughtful research to support your next decision.', items: ['Résumé screening', 'Candidate & Indeed research', 'Administrative research', 'Organized findings for your team'] },
];
export const projects = [
  { title: 'Payroll & GPS audit', category: 'Payroll', label: '01 / REVIEW & RECONCILIATION', summary: 'A clear trail from claimed hours to documented exceptions.', challenge: 'A payroll reviewer needs to understand which technician time entries need a closer look.', approach: 'Compare claimed time with GPS site windows, flag variances, and record questions for management. GPS alone does not establish payable time; travel, breaks and missing signals need review.', outcome: 'A concise exception log with evidence gaps and next actions. Final payroll decisions remain with management.', columns: ['Record', 'Claimed', 'GPS window', 'Variance', 'Next action'], rows: [['TECH-01', '8.0 h', '7.5 h', '0.5 h', 'Check travel time'], ['TECH-02', '8.0 h', '8.0 h', '0.0 h', 'No variance'], ['TECH-03', '7.5 h', '6.5 h', '1.0 h', 'Review missing GPS']], tags: ['Excel', 'Reconciliation', 'Exception log'] },
  { title: 'Daily operations report', category: 'Operations', label: '02 / REPORTING', summary: 'The day’s priorities, progress and follow-ups in one view.', challenge: 'Management needs a readable snapshot of dispatch activity without chasing multiple updates.', approach: 'Group work by status, surface blockers, assign next actions and format a daily handover.', outcome: 'An illustrative management report with clear ownership and outstanding actions.', columns: ['Work item', 'Status', 'Owner', 'Next action'], rows: [['WO-101 / Site A', 'Complete', 'Team A', 'File service notes'], ['WO-102 / Site B', 'In progress', 'Team B', 'Confirm completion'], ['WO-103 / Site C', 'Blocked', 'Dispatch', 'Confirm parts ETA']], tags: ['Daily reporting', 'Dispatch', 'Team coordination'] },
  { title: 'Contract & renewal tracker', category: 'Administration', label: '03 / CONTRACT ADMINISTRATION', summary: 'Renewal dates and billing details that don’t get lost.', challenge: 'Renewals, documents and billing updates are spread across different records.', approach: 'Consolidate renewal dates, illustrative billing amounts, document status and follow-up requirements into a single tracker.', outcome: 'A structured overview that makes upcoming renewals and missing information visible.', columns: ['Client alias', 'Renewal', 'Sample billing', 'Status', 'Follow-up'], rows: [['Client A', '2026-10-01', '$250 / month', 'Review due', 'Request approval'], ['Client B', '2026-11-15', '$400 / month', 'Active', 'Confirm scope'], ['Client C', '2026-12-01', '$300 / month', 'Pending', 'Collect document']], tags: ['Google Sheets', 'Renewals', 'Documentation'] },
  { title: 'Work order & PO tracker', category: 'Operations', label: '04 / OPERATIONAL COORDINATION', summary: 'Connect each job to its purchase order and next step.', challenge: 'A team needs to see which jobs are ready and which are waiting for purchasing updates.', approach: 'Link work orders to purchase orders, dates, owners and outstanding approvals.', outcome: 'A sample tracker that gives the team a shared reference for follow-ups.', columns: ['Work order', 'PO', 'Due', 'Status', 'Next action'], rows: [['WO-201', 'PO-401', '2026-09-14', 'Approved', 'Schedule visit'], ['WO-202', 'PO-402', '2026-09-15', 'Awaiting approval', 'Follow up'], ['WO-203', 'PO-403', '2026-09-16', 'Ordered', 'Confirm delivery']], tags: ['Work orders', 'Purchase orders', 'Tracking'] },
  { title: 'From messy data to clarity', category: 'Administration', label: '05 / DATA ORGANIZATION', summary: 'Consistent records that are easier to search and use.', challenge: 'Inconsistent labels, date formats and duplicate entries make a spreadsheet difficult to trust.', approach: 'Standardize formats, identify duplicates and mark missing values for verification instead of guessing.', outcome: 'A before-and-after sample showing an organized, traceable cleanup.', columns: ['Original entry', 'Clean record', 'Action'], rows: [['client a | 9/14/26 | done', 'Client A | 2026-09-14 | Complete', 'Standardized'], ['CLIENT A | 09/14/2026 | DONE', 'Linked to Client A record', 'Duplicate flagged'], ['client b | ? | pending', 'Client B | Unconfirmed | Pending', 'Date verification needed']], tags: ['Data quality', 'Excel', 'Organization'] },
  { title: 'An organized admin workflow', category: 'Administration', label: '06 / PROCESS & FOLLOW-UPS', summary: 'Give every request a place, an owner and a next action.', challenge: 'Requests arrive by email and chat, making deadlines and follow-ups easy to miss.', approach: 'Capture each request, confirm the priority, organize supporting files and schedule a status check.', outcome: 'A practical sample workflow for a more consistent handover.', columns: ['Stage', 'Action', 'Output'], rows: [['Capture', 'Log request & due date', 'Task record'], ['Organize', 'Assign owner & link files', 'Ready-to-work brief'], ['Follow up', 'Check blockers & update status', 'Progress note'], ['Close', 'Confirm completion & archive', 'Clear handover']], tags: ['Workflow', 'Follow-ups', 'Remote support'] },
];
export const toolGroups = [
  { name: 'Spreadsheets & reporting', tools: ['Microsoft Excel', 'Google Sheets'] },
  { name: 'Everyday collaboration', tools: ['Google Workspace', 'Google Drive', 'Microsoft Outlook', 'Microsoft Teams', 'OneDrive', 'Slack'] },
  { name: 'Operations & documentation', tools: ['signNow', 'Data Basics', 'Data Basics Fleet'] },
  { name: 'Customer support', tools: ['VICI / Smart Dialer', 'CRM / help-desk systems'] },
];
